"""add memory name

Revision ID: f8c1fc9be252
Revises: b942da1196f0
Create Date: 2026-04-06 12:45:26.136961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8c1fc9be252"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("name", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "uq_memories_name_workspace", "memories", ["name", "workspace_id"]
    )
    # ### end Alembic commands ###

    # Pass 1: extract name from "name: content" pattern where unambiguous.
    op.execute(sa.text("""
        UPDATE memories
        SET
            name    = TRIM(SPLIT_PART(content, ':', 1))
        WHERE
            POSITION(':' IN content) > 0
            AND CHAR_LENGTH(TRIM(SPLIT_PART(content, ':', 1))) BETWEEN 3 AND 60
            AND name IS NULL
            AND NOT EXISTS (
                SELECT 1 FROM memories m2
                WHERE m2.workspace_id = memories.workspace_id
                  AND m2.id != memories.id
                  AND POSITION(':' IN m2.content) > 0
                  AND CHAR_LENGTH(TRIM(SPLIT_PART(m2.content, ':', 1))) BETWEEN 3 AND 60
                  AND TRIM(SPLIT_PART(m2.content, ':', 1)) = TRIM(SPLIT_PART(memories.content, ':', 1))
            )
    """))

    op.execute(sa.text("""
       UPDATE memories
       SET
           name    = TRIM(SPLIT_PART(content, '\n', 1))
       WHERE
           POSITION('\n' IN content) > 0
         AND CHAR_LENGTH(TRIM(SPLIT_PART(content, '\n', 1))) BETWEEN 3 AND 60
         AND name IS NULL
         AND NOT EXISTS (
           SELECT 1 FROM memories m2
           WHERE m2.workspace_id = memories.workspace_id
             AND m2.id != memories.id
             AND POSITION('\n' IN m2.content) > 0
             AND CHAR_LENGTH(TRIM(SPLIT_PART(m2.content, '\n', 1))) BETWEEN 3 AND 60
             AND TRIM(SPLIT_PART(m2.content, '\n', 1)) = TRIM(SPLIT_PART(memories.content, '\n', 1))
       )
       """))

    # Pass 2: fill remaining NULLs from the first 60 chars of content.
    op.execute(sa.text("""
        UPDATE memories m
        SET name = CASE 
            WHEN LENGTH(m.content) > 60
            THEN LEFT(TRIM(m.content), 60) || '...'
            ELSE m.content
            END
        WHERE m.name IS NULL
    """))

    op.alter_column("memories", "name", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_memories_name_workspace", "memories", type_="unique")
    op.drop_column("memories", "name")
    # ### end Alembic commands ###
